# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.0.4
maven_group=cc.barnab
archives_name=commandoptimiser
enabled_platforms=fabric,neoforge
# Minecraft properties
min_minecraft_version=26.1
max_minecraft_version=26.1.2
minecraft_version=26.1.2
# Dependencies
fabric_loader_version=0.19.2
neoforge_version=26.1.2.30-beta

